### ISSUE TITLE
wrong public key is being offered when using multiple identities

### ISSUE THREAD

**Issue by emanelif** [moul/advanced-ssh-config#114]
consider the following config

    hosts:
        foo:
            Hostname: hostB
            IdentityFile: ~/.ssh/a
        bar:
            Hostname: hostA
            IdentityFile: ~/.ssh/b
`ssh foo/bar` leads to `Permission denied (publickey).` because the wrong public key is being offered

is that my fault, intended behaviour or assh's fault?

**Comment by moul** [comment]
Hi @emanelif, thank you for your feedback,

Your configuration file looks good, I need to do some tests to figure out where the issue is

**Comment by moul** [comment]
I think #116 fixed this issue too, can you give a try and tell me if both of the issues were addressed ?

**Comment by emanelif** [comment]
I hope I used the correct version. `go get -u github.com/moul/advanced-ssh-config/cmd/assh` should do it, right?
ssh foo/bar is not working then: `Permission denied (publickey).`

**Comment by moul** [comment]
Yep, `go get -u github.com/moul/advanced-ssh-config/cmd/assh` will fetch and compile the latest version in your `$GOPATH/bin` directory, then you need to have `$GOPATH/bin` in your `$PATH` or call the binary using its absolute path to be sure to run this version

response to your **edit1**: :)

response to your **edit2**: the way `assh` is working do not requires agent-forwarding (I personnaly disabled it globally for security reasons), `assh` won't call `ssh hosta -- ssh hostb`, but `ssh hosta -- netcat hostb 22` and use this netcat socket to perform a new ssh connection from the assh hostYep, `go get -u github.com/moul/advanced-ssh-config/cmd/assh` will fetch and compile the latest version in your `$GOPATH/bin` directory, then you need to have `$GOPATH/bin` in your `$PATH` or call the binary using its absolute path to be sure to run this version

response to your **edit1**: :)

response to your **edit2**: the way `assh` is working do not requires agent-forwarding (I personnaly disabled it globally for security reasons), `assh` won't call `ssh hosta -- ssh hostb`, but `ssh hosta -- netcat hostb 22` and use this netcat socket to perform a new ssh connection from the assh host

**Comment by emanelif** [comment]
everything works fine now.

**Comment by moul** [comment]
perfect :) thank you for your feedbacks
