### ISSUE TITLE
Expanded hosts does not use specified user

### ISSUE THREAD

**Issue by rothgar** [moul/advanced-ssh-config#127]
I very well may be doing something wrong (please correct my usage if I am). :grin: 

I am trying to expand multiple raspberry pi hosts I have on my network with a assh.yml configuration with the following.
```yaml
"pi(1|2)":
  Hostname: "%h"
  User: pi
  Inherits:
    - home-net
```

This generates the following in my .ssh/config

```ini
Host pi(1|2)
  Port 22
  User pi
  # HostName: %h
  # Inherits: [home-net]
  # Gateways: [direct, h]
```
User is present in the config however when I try to `ssh pi1` it still prompts for my current user's password. I also tried making the host be similar to the example config with `"pi[1-2]*" but it had the same result when ssh-ing into a pi. It works with pi* but that expands to match too many hosts.

**Comment by moul** [comment]
Hi @rothgar, 

You have a similar issue than #121, I'm trying a big refactor to address what I call "advanced regex" with #122.

For now, I suggest you to replace your current regex with a basic one: `pi(1|2) -> pi*` or do not use regex but templates instead if you only have two hosts

**Comment by moul** [comment]
Closing this issue in favor of #122, please subscribe to the new issue to keep track of the changes
