### ISSUE TITLE
Use args[0] as ProxyCommand

### ISSUE THREAD

**Issue by Skrupellos** [moul/advanced-ssh-config#134]
When writing the `~/.ssh/config` use `args[0]` (the actual name, the application was called with) for the `ProxyCommand` instead of the static `asshBinary`.

**Comment by moul** [comment]
sure, will do

**Comment by jedahan** [comment]
this is not working correctly for me - it is prepending the path from which I called assh, instead of the path of the assh binary

so if i am in /some/dir, it makes the config

/some/dir/assh instead of the same output as `which ssh`

**Comment by moul** [comment]
@jedahan, thank you,

I just removed the absolute path resolving so it now works with 
* absolute paths
* direct binary call with correct `$PATH`

We just need to take care of never call something like `cd /some/where; ./assh build > ~/.ssh/config` which will generate `ProxyCommand ./assh proxy --port=%p %h` which will only works if `ssh` is called always from the same directory

**Comment by jedahan** [comment]
Thank you for the quick fix, and awesome software!
