### ISSUE TITLE
Protocol mismatch

### ISSUE THREAD

**Issue by zacbri** [moul/advanced-ssh-config#158]
Config generation worked fine and I can connect to the servers with plain ssh, but `assh connect` gives the following:

```
__$ assh -V -D connect bm1
DEBU[0000] assh args: [bm1]                             
DEBU[0000] Loading config file '/home/nbr/.ssh/assh.yml' 
DEBU[0000] Loaded config file '/home/nbr/.ssh/assh.yml' (0 + 6 => 6 hosts) 
INFO[0000] Host bm1                                     
INFO[0000]   ControlMaster auto                         
INFO[0000]   ControlPath ~/tmp/.ssh/cm/%h-%p-%r.sock    
INFO[0000]   ControlPersist yes                         
INFO[0000]   IdentitiesOnly yes                         
INFO[0000]   IdentityFile ~/.ssh/id_rsa                 
INFO[0000]   Port 22                                    
INFO[0000]   StrictHostKeyChecking no                   
INFO[0000]   User nbr                                   
INFO[0000]   # HostName: bm1                            
DEBU[0000] Host: {"ControlMaster":"auto","ControlPath":"~/tmp/.ssh/cm/%h-%p-%r.sock","ControlPersist":"yes","IdentitiesOnly":"yes","IdentityFile":"~/.ssh/id_rsa","Port":"22","StrictHostKeyChecking":"no","User":"nbr","HostName":"bm1"} 
DEBU[0000] Proxying                                     
DEBU[0000] Connecting without gateway                   
DEBU[0000] Preparing host object                        
DEBU[0000] Connecting to bm1:22                         
DEBU[0000] Connected to bm1:22                          
SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2

Protocol mismatch.
DEBU[0002] Byte written 60
```

Everything I can find point towards something with netcat, but the connection is made without a gateway.

On the server, I can see this in the logs: `Bad protocol version identification '' from...`

**Comment by moul** [comment]
Hi @zacbri, thank you for your feedback,

The role of `assh connect` is to open a TCP connection to the remote host, the idea is to use the `assh connect` as the [ProxyCommand](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts) feature of the plain `ssh` client and let the `ssh` client handle all the SSH protocol

I think you get this Protocol error because you hit ENTER or something like this; You should have the same behavior by connecting using netcat to the SSH server TCP port: `nc bm1 22` -> [ENTER]

What happen if you enter `ssh -v bm1` ?

**Comment by zacbri** [comment]
Hi,

you're right. I ran some more tests after posting and realised that assh acts as some sort of hook on ssh commands.  
At first I was under the impression I had to use `assh connect` instead of plain ssh everywhere, but that's obviously not the case, `ssh bm1` works fine, as do more advanced use cases with Gateways and failover.

Thanks for the quick reply.

Just to make sure I fully understand your explanation: should I explicitly set `assh connect` as the default ProxyCommand in assh.yml or is that done automatically?

**Comment by moul** [comment]
> At first I was under the impression I had to use assh connect instead of plain ssh everywhere, but that's obviously not the case, ssh bm1 works fine, as do more advanced use cases with Gateways and failover.

Absolutely :) I chose this method over manual `assh binary call` so every programs using libssh, not just `ssh` uses this, so basically, when you type `ssh`, `rsync`, `scp` or if you a third-party program or even a graphical application, the ssh should use your configuration, so now you can easily use multiple gateways with Rsync (which is usually very annoying)

> Just to make sure I fully understand your explanation: should I explicitly set assh connect as the default ProxyCommand in assh.yml or is that done automatically?

This one is automatically added, you can see the generated configuration file by running: `assh config build`, it will print out the `~/.ssh/config` content to your terminal, and you should see a `ProxyCommand: ...assh`, somewhere at the end of the file which is the catch all

**Comment by zacbri** [comment]
That's right.
Thanks for taking time to explain all this.
Great work btw! The gw failover especially is going to make things a lot easier for us.

**Comment by moul** [comment]
:) I will keep your issue as a reminder to add an explanation in the README's FAQ :)
