### ISSUE TITLE
Panic on first run

### ISSUE THREAD

**Issue by scoates** [moul/advanced-ssh-config#171]
I just installed assh via Homebrew, and ran `assh config list` before creating a `assh.yml` file.

It immediately panicked:

```
panic: open /Users/sean/.ssh/assh.yml: no such file or directory [recovered]
       	panic: open /Users/sean/.ssh/assh.yml: no such file or directory
…
```

Not a big deal, but probably best to handle this gracefully.

**Comment by moul** [comment]
Hi @scoates, thanks for the reporting,

I hope this bad experience won't discourage you to try assh :)

**Comment by moul** [comment]
Fixed, thank you
