### ISSUE TITLE
Not able to set PubkeyAcceptedKeyTypes

### ISSUE THREAD

**Issue by sjovang** [moul/advanced-ssh-config#175]
I'm having trouble setting PubkeyAcceptedKeyTypes: +ssh-dss in assh.yml

I have tried setting it both under the defaults-stanza, and as a template. Like so

    defaults:
        ControlMaster: auto
        ControlPath: ~/.ssh/tmp/%C.sock
        ControlPersist: yes
        Port: 22
        ServerAliveInterval: 60
        PubkeyAcceptedKeyTypes: +ssh-dss

    enable-dss:
        HostKeyAlgorithms: +ssh-dss
        PubkeyAcceptedKeyTypes: +ssh-dss

Using ssh -v to connect to a host where this setting is needed still gives me the following error:

    debug1: Skipping ssh-dss key <redacted> - not in PubkeyAcceptedKeyTypes

When I look into ~/.ssh/config I find no trace of this being set:

    Host foo
        HostKeyAlgorithms +ssh-dss
        IdentityFile ~/.ssh/<redacted>
        # HostName: <redacted>
        # Inherits: [enable-dss]

    Host *
        ControlMaster auto
        ControlPath ~/.ssh/tmp/%C.sock
        ControlPersist yes
        Port 22
        ServerAliveInterval 60
        ProxyCommand assh connect --port=%p %h`

**Comment by moul** [comment]
Hey @sjovang,

I just added this field to the config parser, can you try again?

**Comment by sjovang** [comment]
Works perfectly. Thanks for the swift resolution if the issue! 👍
