### ISSUE TITLE
ASSH creates empty folder of SSH gateway

### ISSUE THREAD

**Issue by keefetang** [moul/advanced-ssh-config#184]
Machine config:

    $ system_profiler SPSoftwareDataType
    Software:

        System Software Overview:

          System Version: macOS 10.12.1 (16B2555)
          Kernel Version: Darwin 16.1.0
          Boot Volume: macOS
          Boot Mode: Normal
          Computer Name: ***
          User Name: ***
          Secure Virtual Memory: Enabled
          System Integrity Protection: Disabled
          Time since boot: 41 minutes
    
    $ alias ssh
    alias ssh='assh wrapper ssh'

    $ brew info assh
    assh: stable 2.4.1 (bottled), HEAD
    Advanced SSH config - Regex, aliases, gateways, includes and dynamic hosts
    https://github.com/moul/advanced-ssh-config
    /usr/local/Cellar/assh/2.4.1 (2 files, 6.5M) *
      Built from source on 2016-09-21 at 22:10:28
    From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/assh.rb
    ==> Dependencies
    Build: go ✔

    $ brew info go
    go: stable 1.7.4 (bottled), devel 1.8beta1, HEAD
    The Go programming language
    https://golang.org
    /usr/local/Cellar/go/1.7.4 (6,438 files, 250.7M) *
      Poured from bottle on 2016-12-05 at 07:23:06
    From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb
    ==> Requirements
    Build: git ✔
    Required: macOS >= 10.8 ✔
    ==> Options
    --without-cgo
            Build without cgo (also disables race detector)
    --without-godoc
            godoc will not be installed for you
    --without-race
            Build without race detector
    --devel
            Install development version 1.8beta1
    --HEAD
            Install HEAD version
    ==> Caveats
    As of go 1.2, a valid GOPATH is required to use the `go get` command:
      https://golang.org/doc/code.html#GOPATH

    You may wish to add the GOROOT-based install location to your PATH:
      export PATH=$PATH:/usr/local/opt/go/libexec/bin

ASSH config:

    Hosts:
      host:
        Hostname: [hostname]
        Inherits:
          - user
    templates:
      gateway:
        Gateways:
          - [gateway-hostname]
      user:
        User: [username]
        Inherits:
          - gateway
    defaults:
      Port: 22
      User: [user]
      StrictHostKeyChecking: no
      IdentityFile: [keyname]
      ForwardX11: yes
      ForwardX11Trusted: yes
      ForwardAgent: yes
      Hooks:
        OnConnect:
          - notify New SSH connection to {{.Host.Prototype}}.
        OnDisconnect:
          - "notify SSH connection to {{.Host.Name}} closed, {{ .Stats.WrittenBytes }} bytes written in {{ .Stats.ConnectionDuration }} ({{ .Stats.AverageSpeed }})"

Issue description:

Every time ssh in invoked, an empty folder with the name of the gateway is created on the current working directory.

This seems to happen even when the gateway is specified in the ssh command such as `ssh host/gateway`

**Comment by moul** [comment]
Hi @keefetang,

This "was" a feature, but not as good as I imagined initially; so I disabled this behavior yesterday, see #173

While waiting for a new release, you can disable this action by adding `NoControlMasterMkdir: true` in the `defaults` section of your `assh.yml` file

**Comment by keefetang** [comment]
Thanks @moul, that does stop the folder form being created.
