### ISSUE TITLE
Multiple SSH forwards don't work when specified with -L

### ISSUE THREAD

**Issue by bachya** [moul/advanced-ssh-config#185]
I have the following entry in my generated SSH config:

```
Host home
  User root
  # HostName: myhost.com
```

When I run this command (to forward multiple ports):

`ssh -L 9998:localhost:22 -L 9999:localhost:22 home -N -v -v`

(where `ssh` is aliased to `assh wrapper ssh`)

...I only see the last `-L` option specified in the output:

```
debug1: Local connections to LOCALHOST:9999 forwarded to remote address 192.168.1.121:22
debug1: Local forwarding listening on ::1 port 9999.
debug2: fd 6 setting O_NONBLOCK
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 9999.
```

I can confirm that when I use the system `/usr/bin/ssh`, both forwards are activated correctly.

This may be related to https://github.com/moul/advanced-ssh-config/issues/119 – not sure.

**Comment by moul** [comment]
Ho @bachya, thanks for your feedback,

I just opened a PR (#186) with a fix

**Comment by bachya** [comment]
Hi @moul – appreciate the quick turnaround! It looks like #186 fixes this; when I run the original command now:

`ssh -L 9998:localhost:22 -L 9999:localhost:22 home -N -v -v`

...I get both ports forwarded:

```
debug1: Local connections to LOCALHOST:9998 forwarded to remote address 192.168.1.121:9998
debug1: Local forwarding listening on ::1 port 9998.
debug2: fd 6 setting O_NONBLOCK
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 9999.
debug2: fd 7 setting O_NONBLOCK
debug1: channel 1: new [port listener]
debug1: Local connections to LOCALHOST:9999 forwarded to remote address 192.168.1.121:9999
debug1: Local forwarding listening on ::1 port 9999.
debug2: fd 8 setting O_NONBLOCK
debug1: channel 2: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 8088.
```

Thanks so much!

**Comment by moul** [comment]
Perfect :)
