### ISSUE TITLE
Document usage of assh in 3rd party tools

### ISSUE THREAD

**Issue by cnf** [moul/advanced-ssh-config#196]
Hi,

I would like to contribute some of my config for 3rd party tools to use assh, but I am uncertain where to put it. Do you want it in the README.md, or would you prefer a separate 3RDPARTY-INTEGRATIONS.md or something for this?

**Comment by moul** [comment]
Awesome, for now I prefer to keep everything in the README
Thanks

**Comment by cnf** [comment]
PR added

**Comment by moul** [comment]
Merged, thanks a lot,

I'm looking forward to more examples so I can better understand the different usages
