### ISSUE TITLE
New host breaks ssh

### ISSUE THREAD

**Issue by pikeas** [moul/advanced-ssh-config#215]
I'm running a one-liner to update a file across a group of servers:

    $ for i in {1..10}; do scp file server$i.domain.com:/etc; done
    file                                                                                                          100% 2168    11.1KB/s   00:00
    file                                                                                                          100% 2168    11.1KB/s   00:00
    ...
    The authenticity of host 'server7.domain.com (<no hostip for proxy command>)' can't be established.
    ECDSA key fingerprint is SHA256:/....
    Are you sure you want to continue connecting (yes/no)? yes
    Warning: Permanently added 'server7.domain.com' (ECDSA) to the list of known hosts.
    file                                                                                                          100% 2168    11.1KB/s   00:00
    WARN[0000] '~/.ssh/config' has been rewritten.  SSH needs to be restarted.  See https://github.com/moul/advanced-ssh-config/issues/122 for more information.
    /Users/apikeas/.ssh/config: line 62: Bad configuration option: ver8.domain.com,
    /Users/apikeas/.ssh/config: terminating, 1 bad configuration options

This is reproducible - the first unknown host connects successfully, the next unknown host causes the above failure. The error on line 62 is always a truncated host name.

**Comment by moul** [comment]
Fixed :)

Thanks for your feedback!
