### ISSUE TITLE
OpenSSH caught up and added a "Include" directive as of v7.3

### ISSUE THREAD

**Issue by ypid** [moul/advanced-ssh-config#224]
OpenSSH finally caught up:

* "ssh(1): Add an Include directive for ssh_config(5) files.", ref: https://www.openssh.com/txt/release-7.3

Can you maybe update the readme and repo description to raise attention for this?

**Comment by moul** [comment]
Yes, sure,

Do you want to make a PR?

**Comment by ypid** [comment]
Sure. Can you update the repo description as well?

**Comment by moul** [comment]
Done, thanks
