### ISSUE TITLE
Don't use "nc", use "-W"

### ISSUE THREAD

**Issue by vincentbernat** [moul/advanced-ssh-config#227]
Hey!

Instead of using `nc`, please use `-W`: `ssh .... -W %h:%p`. When using `nc`, you add an unnecessary process which may stay around when not needed anymore (when using the class netcat instead of OpenBSD's one).

**Comment by vincentbernat** [comment]
Hummm, it seems that assh is already using `-W`, despite the numerous examples using `nc`.

**Comment by moul** [comment]
Hey @vincentbernat, thanks for you feedback,

Actually, assh will try to use built-in socket first, but allow the user to use a custom "socket opener"
I will try to update the `README.md` to be more clear on this subject
