### ISSUE TITLE
graphviz ignores *-masks

### ISSUE THREAD

**Issue by neopaf** [moul/advanced-ssh-config#228]
```
rualpe-ws:~ paf$ cat ~/.ssh/assh.yml
hosts:
 customer*:
  hostname: 1.1.1.1
 tricky:
  gateways: customerterm

rualpe-ws:~ paf$ assh config graphviz 
digraph G {
	"tricky" [ color=blue ];

}
rualpe-ws:~ paf$ 
```

one would expect the relation to be shown, kinda like this (see also label):
```
digraph G {
	"customer*" [ color=blue ];
	"tricky" [ color=blue ] -> "customer*" [label="customerterm"];

}
```

(great tool, thanks!)

**Comment by moul** [comment]
Hey @neopaf,

I wasn't sure about how to handle wildcards in the graph, I will try some experiment, and if the behavior looks strange I will probably let the option to do it toggleable through a CLI parameter

Thank you for your feedback

**Comment by neopaf** [comment]
Manfred, I feel you have all the necessary code that matches wildcards when you search the gateway name in list of hosts.

Same search may be applied to replace "customerterm" with "customer*" in my example.

**Comment by neopaf** [comment]
thanks for your cool tool again. I've put more people around me to use it. they were jumping with joy.
you've saved thousands of scp-scp-scp per year for all of us!

**Comment by moul** [comment]
Hi @neopaf,

Support added with #233, the behavior can be disabled using `--no-resolve-wildcard`

Can you try the latest version and give me your feedback?

**Comment by neopaf** [comment]
```
rualpe-ws:gcs paf$ assh -h
NAME:
   assh - advanced ssh config

USAGE:
   assh [global options] command [command options] [arguments...]

VERSION:
   2.6.0+dev (HEAD)
```

made me happy on in this regard.
now lines go exactly as discussed, thank you, Manfred.

I've also noticed one other small detail, that may be worth showing, will report it separately. 

I move we close this issue.

**Comment by neopaf** [comment]
for history
![a](https://cloud.githubusercontent.com/assets/4362564/24035929/9237f62a-0b08-11e7-940c-d9ac366222c7.png)
