### ISSUE TITLE
Failed to load known-hosts file during config build

### ISSUE THREAD

**Issue by austinbutler** [moul/advanced-ssh-config#230]
I am trying to use this for the first time, so I went to generate the config, but I get an error about the known-hosts file being missing. Since I've never used assh before, yeah that file would be missing.

```sh
assh config build > ~/.ssh/config                                                                                           
ERRO[0000] Failed to load known-hosts file: open /Users/abutler/.ssh/assh_known_hosts: no such file or directory
```

This is with 2.6.0.

```sh
assh --version                                                                                                              
assh version 2.6.0 (HEAD)
```

I was able to get around it with `--ignore-known-hosts`, but shouldn't the build process be OK with a missing known-hosts file?

**Comment by moul** [comment]
Hi @austinbutler, just fixed with #232 
Thanks for your feedback
