### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by Falkor** [moul/advanced-ssh-config#231]
I installed `assh` using Homebrew and I try to make the notifications working under Mac OS. 
The following configuration adapted from the README: 

~~~yaml
defaults:
  Hooks:
    OnConnect:
    - notify New SSH connection to {{.Host.Prototype}}.
    OnDisconnect:
    - notify SSH connection to {{.Host.Name}} closed, {{ .Stats.WrittenBytes }} bytes written in {{ .Stats.ConnectionDuration }} ({{ .Stats.AverageSpeed }})
~~~

Does not work. Have I missed something?

**Comment by Falkor** [comment]
Installation of the [gnotifier](https://github.com/haklop/gnotifier) lib seems to have solve the issue:

~~~bash
$> brew install go
$> export GOPATH=${XDG_CACHE_HOME}/go    # To be placed in you favorite shell config
$> go get github.com/haklop/gnotifier
~~~

Most probably the installation notes should be updated accordingly ?

**Comment by Falkor** [comment]
I still have transient issue (sometimes the notification popup appears, sometimes not). 
More importantly, I was wondering is there is a way to filter the hosts for which such notification is provided. For instance, it is rather annoying to have it enabled systematically upon all push/pull actions on a Git server. Is there a way to filter out targeted servers?

**Comment by moul** [comment]
Hi @Falkor, thank you for your feedbac,

> Installation of the gnotifier lib seems to have solved the issue:
> Most probably the installation notes should be updated accordingly ?

Done in 3d48b63

> I still have transient issues (sometimes the notification popup appears, sometimes not).

Do you have more info ?

In my case (on OS X), seems stable,
but keep in mind that if you use a `ControlMaster` socket, you won't necessarily have notifications each time you close an SSH connection

Keep me informed if you have more details about when and why it happens

> For instance, it is rather annoying to have it enabled systematically upon all push/pull actions on a Git server. Is there a way to filter out targeted servers?

Yes, every `assh` settings can be set globally (in the `defaults` section or per-host.

For now, the only option to do it is to remove the default configuration and configure each host independently (can be eased with inheritance)

```yaml
github.com:

myserver:
  Hooks:
    OnConnect:
    - notify blah blah

defaults:
```

But I will update the configuration to allow keep a default settings but disable it only on some hosts, something like this (not working right now)

```yaml
github.com:
  Hooks: none

defaults:
  Hooks:
    OnConnect:
    - notify blah blah
```

**Comment by Falkor** [comment]
@moul Excellent, and you're right, the `ControlMaster`socket  was the reason why the notification were not working as expected.

**Comment by moul** [comment]
Closing this issue, I will continue to work on the `disable-per-host` feature in #234 

Feel free to reopen if needed
