### ISSUE TITLE
Run ResolveCommand on gateway

### ISSUE THREAD

**Issue by sergei-dyshel** [moul/advanced-ssh-config#247]
**Problem**: I want `ResolveCommand` to dynamically resolve hostname but in my case it must be executed  on gateway. In other words, when I run
```
ssh x.somehost/somegate
```
I want either of:
1) `ResolveCommand` to be executed on `somegate` server.
2) `ResolveCommand` to receive `somegate` as parameter (e.g. via `%g` parameter in addition to `%h`) so it can access `somegate` and execute some command there.

What am I doing now is some workaround for (2): I'm using
```
ssh x.somehost.somegate/somegate
```
so my `ResolveCommand` extracts `somegate` from the hostname. That's not that bad but it would be nice to type `somegate` only once :smile:

**Comment by moul** [comment]
Hi @sergei-dyshel, thank you for your feedback,

---

Some clarifications, first:

Today, `ssh x.somehost/somegate` will result in two successive `ssh` calls:

1. `ssh somegate`, which will open a TCP connection to the SSH port of `x.somehost.somegate`
2. `ssh x.somehost` using the first connection like a TCP proxy

It implies that `ResolveCommand` is run twice, hence, on the gateway

But you will only have the current host in the context passed to your `ResolveCommand`.

---

I can probably add a new `%g` parameter with the current gateway, but keep in mind that the `ResolveCommand` will be called twice if you hold it in the `defaults:` section of your `assh.yml` file; I will try it on a new branch

For gateway chaining, I will use the following:

`ssh a/b/c` results in three calls to `ResolveCommand`, in this order:

1. `%h = "c"` + `%g = ""`
2. `%h = "b"` + `%g = "c"`
3. `%h = "a"` + `%g = "b/c"`
