### ISSUE TITLE
Then connecting some hosts from known list get weird output

### ISSUE THREAD

**Issue by spellanser** [moul/advanced-ssh-config#252]
Hi!
First of all, thank you for nice solution to work with ssh-config.
I just started using assh, so i can miss something, but then i connect to two hosts from ssh-config entry and assh_known_hosts list i obtain a lot of output starting with INFO[000] which contain big part of .ssh/config file. 
```INFO[0000] Host door-aaa-2
INFO[0000]   AddKeysToAgent yes
INFO[0000]   IdentityFile ~/.ssh/id_rsa
INFO[0000]   Port 22
INFO[0000]   Protocol 2
INFO[0000]   ServerAliveCountMax 30
INFO[0000]   ServerAliveInterval 60
INFO[0000]   UseKeychain yes
INFO[0000]   User login
INFO[0000]   # HostName: door-aaa-2.domain.com
INFO[0000]   # KnownHosts: [door-aaa-2, ....]
INFO[0000]  and so on ... 
```

Part of my .ssh/config: 
```
Host door-[a-z]*-[0-9]
  User login
  # HostName: %h.domain.com
  # KnownHosts: [door-aaa-1, door-aaa-2, door-bbb-1, door-bbb-2] 

Host door-aaa-2
  User login
  # HostName: %h.domain.com
  # KnownHostOf: door-[a-z]*-[0-9]

Host door-aaa-1
  User login
  # HostName: %h.domain.com
  # KnownHostOf: door-[a-z]*-[0-9]

Host door-bbb-1
  User login
  # HostName: %h.domain.com
  # KnownHostOf: door-[a-z]*-[0-9]

Host door-bbb-2
  User login
  # HostName: %h.domain.com
  # KnownHostOf: door-[a-z]*-[0-9]

```

So then i ssh door-aaa-[1,2] i got weird output with INFO, but then ssh to door-bbb-[1,2] no output provided from assh. 

What i am doing wrong?)

**Comment by spellanser** [comment]
Hello! 
Is there any progress?

**Comment by moul** [comment]
Hi @spellanser,

It looks like `assh` is printing some debug output, this can be achieved by calling `ssh` with `-v` argument, by setting the `ASSH_DEBUG=1` env var or more probably, because your version of `assh` has some hardcoded debug outputs :)

---

Which version are you using (`assh --version`) ?

I just tried to reproduce your scenario with this `assh.yml` file:

```yaml
hosts:
  "door-[a-z]*-[0-9]":
    User: login
    HostName: "%h.127.0.0.1.xip.io"
```

```console
$ ssh door-aaa-1
New SSH connection to login@door-aaa-1.127.0.0.1.xip.io:22 at 2017-09-20 10:06:18.013550686 +0200 CEST

$ ssh door-bbb-1
New SSH connection to login@door-bbb-1.127.0.0.1.xip.io:22 at 2017-09-20 10:06:29.067242458 +0200 CEST
Password:

$ ssh door-bbb-2
New SSH connection to login@door-bbb-2.127.0.0.1.xip.io:22 at 2017-09-20 10:06:32.469944125 +0200 CEST
Passowrd:
```

**Comment by spellanser** [comment]
Hi @moul 
`assh version 2.6.0 (HEAD)`
ASSH_DEBUG var empty (not exist).

**Comment by moul** [comment]
Can you paste your full `assh.yml` file (here or privately) ?

**Comment by spellanser** [comment]
I can provide the part, which contains a description of the problematic hosts:

`hosts: 

  "door-[a-z]*-[0-9]":
    Hostname: "%h.****.com"
    User: spellanser

defaults: 
  Port: 22
  Protocol: 2 
  IdentityFile: ~/.ssh/id_rsa
  User: user
  AddKeysToAgent: yes
  UseKeychain: yes
  ServerAliveINterval: 60
  ServerAliveCountMax: 30
  ForwardAgent: yes
  Hooks:
    # Automatically backup ~/.ssh/config
    BeforeConfigWrite:
      - 'exec set -x; cp {{.SSHConfigPath}} {{.SSHConfigPath}}.bkp'`

**Comment by moul** [comment]
I updated the logging level of most of this kind of messages

This should not happen anymore

Else, please ping me
