### ISSUE TITLE
Multiple Gateways Connect to Each even after fist connection is successful 

### ISSUE THREAD

**Issue by dewab** [moul/advanced-ssh-config#263]
I'm running into an issue with the fallback of multiple gateways.  It appears that assh connects to each gateway even if the first is successful.  This may be silent if the second gateway is resolvable and connectable, however in my case, the second gateway is only accessible from outside my network.  Even if the second gateway is resolvable, going through sshd logs, I see that the connection is still made, although it doesn't appear to do anything afterwards, making the second connection "silent".

```yaml
hosts:
  test:
    Hostname: hosta
    User: heimdall
    ForwardX11: no
    Gateways:
      - direct
      - hostb
```

```console
$ ssh test uptime
 12:27:34 up 57 days,  3:25, 15 users,  load average: 2.82, 2.71, 2.93
ssh_exchange_identification: Connection closed by remote host
ERRO[0000] Cannot use gateway 'hostb': exit status 255
FATA[0000] Proxy error: No such available gateway
```

**Comment by dewab** [comment]
Not sure if this helpful or not, but here's the output with debugging enabled:

$ ASSH_DEBUG=true ssh test-gateways uptime
DEBU[0000] Wrapper called with bin=/usr/bin/ssh target=test-gateways command=[uptime] options=[], args=[ssh test-gateways uptime]
DEBU[0000] Loading config file '/Users/Daniel/.ssh/assh.yml'
DEBU[0000] Loaded config file '/Users/Daniel/.ssh/assh.yml' (0 + 1 => 1 hosts)
DEBU[0000] The configuration file is outdated, rebuilding it before calling ssh
DEBU[0000] Writing SSH config file to "/Users/Daniel/.ssh/config"
DEBU[0000] assh args: [test-gateways]
DEBU[0000] Loading config file '/Users/Daniel/.ssh/assh.yml'
DEBU[0000] Loaded config file '/Users/Daniel/.ssh/assh.yml' (0 + 1 => 1 hosts)
DEBU[0000] getHostByName direct matching: "test-gateways"
INFO[0000] Host test-gateways
INFO[0000]   ForwardX11 no
INFO[0000]   Port 22
INFO[0000]   User heimdall
INFO[0000]   # HostName: 192.168.1.11
INFO[0000]   # Gateways: [direct, 192.168.1.10]
DEBU[0000] Host: {"ForwardX11":"no","Port":"22","User":"heimdall","HostName":"192.168.1.11","Gateways":["direct","192.168.1.10"],"Hooks":{}}
DEBU[0000] Proxying
DEBU[0000] Trying gateways: [direct 192.168.1.10]
DEBU[0000] Preparing host object
DEBU[0000] Calling BeforeConnect hooks
DEBU[0000] Connecting to 192.168.1.11:22
DEBU[0000] Connected to 192.168.1.11:22
DEBU[0000] Calling OnConnect hooks
 08:38:09 up 24 days,  2:26,  0 users,  load average: 0.24, 0.06, 0.02
DEBU[0002] Calling OnDisconnect hooks
DEBU[0002] Byte written 2709
DEBU[0002] Using gateway '192.168.1.10': ssh -W 192.168.1.11:22 %name
DEBU[0002] ProxyCommand: ssh -W 192.168.1.11:22 192.168.1.10
[523][Daniel@snotra ~/.ssh] $ DEBU[0000] assh args: [192.168.1.10]
DEBU[0000] Loading config file '/Users/Daniel/.ssh/assh.yml'
DEBU[0000] Loaded config file '/Users/Daniel/.ssh/assh.yml' (0 + 1 => 1 hosts)
INFO[0000] Host 192.168.1.10
INFO[0000]   Port 22
INFO[0000]   # HostName: 192.168.1.10
DEBU[0000] Host: {"Port":"22","HostName":"192.168.1.10","Hooks":{}}
DEBU[0000] Proxying
DEBU[0000] Connecting without gateway
DEBU[0000] Preparing host object
DEBU[0000] Calling BeforeConnect hooks
DEBU[0000] Connecting to 192.168.1.10:22
DEBU[0000] Connected to 192.168.1.10:22
DEBU[0000] Calling OnConnect hooks
DEBU[0000] Calling OnDisconnect hooks
DEBU[0000] Byte written 2829

**Comment by 4wrxb** [comment]
I tested this and found it only applied to the "direct" gateways. Regardless of what comes before it any gateway after direct will be tried even if the direct connection succeeded.

Adding a missing return fixed the issue for me.

**Comment by dewab** [comment]
Any chance someone could review commit 68f086ef81f84e16698658fdeaa1b7b0e115bfcb ?

Thanks!

**Comment by moul** [comment]
@dewab I cherry-picked 68f086e in #285, and merged the PR, thank you 👍

**Comment by dewab** [comment]
That looks to have resolved the multiple connections!  Thanks to you and @4wrxb <https://github.com/4wrxb> to tracking down and patching this one!

-D

**Comment by moul** [comment]
every credits for @4wrxb, and sorry for the delayed review
