### ISSUE TITLE
Username aliases

### ISSUE THREAD

**Issue by sergei-dyshel** [moul/advanced-ssh-config#266]
Is it possible/good idea to allow aliases for user names so that, for example, running `ssh r@host` would expand to `ssh root@host` automatically?

**Comment by moul** [comment]
Hi @sergei-dyshel,

From what I know, it's not possible to override a user directly passed to the `ssh` command from the command line; the priority is `command line > host-specific configuration > global configuration`.

It is possible to allow username aliasing when using the `assh wrapper`, so it will only work when using a terminal and having the proper configuration.
It won't work with other binaries using the libssh itself (`scp`, `rsync`, and everything with a graphical interface.

I like the idea. However, I think it will introduce some inconsistency in the usage of ssh.
