### ISSUE TITLE
Add a --init option

### ISSUE THREAD

**Issue by moul** [moul/advanced-ssh-config#30]
- [ ] convert existing `.ssh/config` file to `.ssh/config.advanced`
- [ ] append `ProxyCommand` linking to absolute path of `$0`
- [ ] add install script and documentation

**Comment by groundnuty** [comment]
>  convert existing .ssh/config file to .ssh/config.advanced
this was never added, was it?

**Comment by moul** [comment]
It wasn’t

It can be done quite easily with hacks,
but the best way to do it is to redesign a little bit the ˋconfig` package to make it able to Marshall/Unmarshall both file formats (this should be helpful for other issues)

That’s something I can try to do if nobody else do it before
