### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by moul** [moul/advanced-ssh-config#31]
- [x] Add a logo
- [ ] Add a screenshot
- [ ] Move demo in the top
- [ ] Simplify and make more important the install guide (Depends on #30)
- [ ] Add a schema showing gateways
- [ ] Add a comparison table
- [ ] Add more examples with documentation
- [ ] Add example for each commands

**Comment by obormot** [comment]
Also in the "First Run" section the recommendation is to execute "assh build -f" that unconditionally overwrites the user's .ssh/config. The README should mention this behavior or recommend backing up the existing file first.
