### ISSUE TITLE
Defining Sections in Included Files

### ISSUE THREAD

**Issue by nfarrar** [moul/advanced-ssh-config#36]
I'm trying to modularize my config by host, i.e:

    # ~/.ssh/config.advanced
    Includes = ~/.ssh/host/host1/config.advanced
    Includes = ~/.ssh/host/host2/config.advanced
    Includes = ~/.ssh/host/host3/config.advanced

    [default]
    User = $USER
    Port = 22
    PubkeyAuthentication = yes
    IdentityFile = ~/.ssh/id_rsa
    ProxyCommand = assh connect %h --port=%p
    
However, it appears that `Includes` must be used *in* a defined section and sections cannot be declared in a file included with `Includes`. Curious if this is correct, and if so why?

Similarly, is there anyway to include configuration files based on a pattern, i.e:

    # includes all files in ~/.ssh/config.advanced
    Includes ~/.ssh/host/**/config.advanced

The specific use case is with my vcsh versioned dotfiles - configs can be broken up into very specific 'subjects' then put on specific hosts - essentially I want to use vcsh to clone sets of ssh config/keys directly to `~/.ssh/<host>/`, set a hook to automatically rebuild `~/.ssh/config` each time I check one out or update one (on any host) and use the same (host independent) `~/.ssh/config.advanced` file across all the hosts. Possible?

**Comment by moul** [comment]
Nice idea, I will try to improve this part and add a better example

**Comment by moul** [comment]
You can already try using:

```ini
[default]
Includes = ~/.ssh/host/host1/config.advanced ~/.ssh/host/host2/config.advanced ~/.ssh/host/host3/config.advanced
User = $USER
Port = 22
PubkeyAuthentication = yes
IdentityFile = ~/.ssh/id_rsa
ProxyCommand = assh connect %h --port=%p
```

The `Includes` directive is inside the `[default]` section, but it accepts new host `sections`, I will try to allow the `Includes` directive to be used outside of the `[default]` section, so it will be less confusing

I will implement globing to support `~/.ssh/host/**/config.advanced`

**Comment by moul** [comment]
Actually I can't put the `Includes` directive outside of a section header, I got the following error: `File contains no section headers.`

Unless I stop to use the [ConfigParser](https://docs.python.org/2/library/configparser.html) Python module, we need to find an alternative, I propose two solutions:

1. We continue to use the `Includes` directive in the `[default]` section and I improve documentation and examples
2. I create a dedicated `[includes]` section, so it may be easier to understand where to put the `Includes` directive

What do you think about this ?

**Comment by moul** [comment]
Now supporting globbing

**Comment by moul** [comment]
Released in https://github.com/moul/advanced-ssh-config/releases/tag/v1.1.0

**Comment by moul** [comment]
**assh 2.0** is out now, It's a complete refactor in Golang

Since your issue was opened for the **1.x** version in Python, I'm closing it now, do not hesitate to reopen it if needed

The `includes` was completely rewritten and is now more flexible and also more reliable
