### ISSUE TITLE
Debugging & Verbose Information - Difficulty Troubleshooting

### ISSUE THREAD

**Issue by nfarrar** [moul/advanced-ssh-config#38]
I'm trying to get some more debugging information out of assh. I'm having some weird issues when generating `~/.ssh/config` and am not sure why they are occurring.

I've tried several combinations of the `-l` flag and `--verbose`, and both at the same time:

    assh build -c ~/.ssh/config.test -c ~/.ssh/config.test --verbose --log_level=DEBUG

However, I never get any debugging or verbose output.

My `~/.ssh/config.advanced` file currently looks like:
```
[default]
User = $USER
Port = 22
PubkeyAuthentication = yes
IdentityFile = ~/.ssh/id_rsa
Includes = test_hosts/**/config.advanced
```

And ~/.ssh/test_hosts/example01/config.advanced
```
[example01]
hostname = host1.example.com
user = user01
Port = 2222
IdentityFile = ~/.ssh/id_rsa
```

And `~/.ssh/test_hosts/example02/config.advanced`:
```
[example02]
hostname = host2.example.com
user = user02
Port = 4444
IdentityFile = ~/.ssh/id_rsa
```

Running `assh build -c ~/.ssh/config.test -c ~/.ssh/config.test --verbose --log_level=DEBUG` results in the following `~/.ssh/config.test` file:

```
# assh version: 1.1.0

Host example01
  identityfile ~/.ssh/id_rsa
  port 2222
  user user01
  # hostname host1.example.com

Host example02
  identityfile ~/.ssh/id_rsa
  port 4444
  user user02
  # hostname host2.example.com

Host *
  identityfile ~/.ssh/id_rsa
  port 22
  proxycommand assh connect %h --port=%p
  pubkeyauthentication yes
  user $USER
```

- The hostname from each included file is commented out.
- The $USER value from `~/.config.advanced` `[default]` is not properly inserted.

On a similar but unrelated note - unless the first line of `~/.ssh/config` is `# assh version: 1.1.0` (regardless of whether we are rebuilding that file or a separate file) the build command will produce an error and refuse to generate the configuration file (unless the `-f` flag is provided). I didn't see any information in the documentation on this and it took me awhile to figure out.

**Comment by moul** [comment]
yes, it's definitively not clear, actually, the debugging feature are only related to the `connect` command but not for the `build` command

I'm actually working on the new Golang version of **assh**, and I will improve the build-related debugging messages

---

About your issue, the hostname is commented out in the .ssh/config file, it is related to the way I manage custom hostnames in the Python version of **assh**, I will try to get rid of this hack in the Golang version and use the real hostname without any comment, but don't care about this comment, while you are using `proxycommand assh connect %h --port=%p', the commented-out hostname will be used by assh !

about the **$USER** value, it's a little bit strange, still in the Python version, this value is only resolved once when calling **connect**, the **build** command won't expand variables in the configuration file.

You should be able to only use the **assh** command, to build the initial version of the configuration file, then you don't have to use assh manually, that's how I'm using it, I never call any **assh** command manually, I'm always using the standard **ssh** command which will call the **assh** binary using the `proxycommand` in the configuration :)

In the Golang version, I will try to remove as most as possible amount of direct calls to assh, so the solution will be fully transparent, stay tuned!

**Comment by moul** [comment]
**assh 2.0** is out now, It's a complete refactor in Golang

Since your issue was opened for the **1.x** version in Python, I'm closing it now, do not hesitate to reopen it if needed

The debugging/logging was completely rewritten too, you may check it using `assh -D proxy myserver`

**Comment by liv3010m** [comment]
Hi there,

Is the issue of the commented hostname still expected on current?
I'm running:
assh version: 2.8.0+dev (HEAD)
Go version: go1.12.7
Python version: 2.7
WSL
Because generating a .ssh/config still comments out the hostname field.

Olivia
