### ISSUE TITLE
Document how to configure the system to parse /etc/hosts when resolving host

### ISSUE THREAD

**Issue by moul** [moul/advanced-ssh-config#47]

**Comment by Skrupellos** [comment]
It's not the job of the application to parse `/etc/hosts` by their own. The Admin can even configure his system to ignore the hosts file in `/etc/nsswitch.conf`. So, I would suggest to close this issue (and not implement it).

**Comment by moul** [comment]
Interesting, 

I also think it will be definitely better to accomplish resolve using system's resolving system,

I let this issue open so I can document this in the README.md
