### ISSUE TITLE
When establishing initial connection to server [enter] isn't working

### ISSUE THREAD

**Issue by davidpelaez** [moul/advanced-ssh-config#53]
When first connecting to a new node the server's key must be accepted. I type yes but the enter key doesn't behave and end up printing something else (escaped character?), here's a sample of the output:

```
The authenticity of host 'prod (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is ec:16:5c:6f:71:1e:55:96:09:62:13:dc:a4:73:6a:a0.
Are you sure you want to continue connecting (yes/no)? yes^M^M^M^C
```

The yes command is not always sent. Sometimes on the next try the security prompt no longer shows, in others it keep reprompting and I cannot tell the difference.

**Comment by moul** [comment]
For now, I can't reproduce the bug

But since I manipulate *inputs*/*outputs*, a bug may clearly exist here

I need more info to fix this

```console
$ ssh 212.47.227.79
The authenticity of host '212.47.227.79 (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is d2:e9:fe:75:eb:5d:2d:80:d9:52:ef:d6:0c:92:13:1f.
+--[ RSA 2048]----+
|                 |
|                 |
|            o E  |
|       . . = = . |
|      . S + * +  |
|       o   . = +.|
|        .   . = =|
|       .   . o +.|
|        ...  .o .|
+-----------------+
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '212.47.227.79' (RSA) to the list of known hosts.
Host key fingerprint is d2:e9:fe:75:eb:5d:2d:80:d9:52:ef:d6:0c:92:13:1f
+--[ RSA 2048]----+
|                 |
|                 |
|            o E  |
|       . . = = . |
|      . S + * +  |
|       o   . = +.|
|        .   . = =|
|       .   . o +.|
|        ...  .o .|
+-----------------+

root@goofy-carson ~ # logout
Shared connection to 212.47.227.79 closed.
$ logout
```

**Comment by davidpelaez** [comment]
I understand, right now I don't have a working config because I cannot find a way to make inheritance work so I cannot provide more info at the moment. Any hints into what extra info could be helpful?

**Comment by moul** [comment]
You can try to run ssh in verbose mode: `ssh -vv ...` we will get more info from *assh* and *ssh*

For now I'm only looking for a repetitive case

Also if you identify an host with the error, you can try to forget the host keys and retry a "first" connection (`ssh-keygen -R hostname`)

**Comment by davidpelaez** [comment]
I think this was a minor bug in tmux, I cannot replicate it anymore apparently after restarting my session. Sorry for the inconvenience.
