### ISSUE TITLE
Document how to configure the system to add mDNS support

### ISSUE THREAD

**Issue by moul** [moul/advanced-ssh-config#90]

**Comment by Skrupellos** [comment]
Same as for #47 . The admin should decide whether to use mDNS or not (he is the only one to start the avahi daemon anyway). If the admin wan's to use mDNS, he can add `hosts:       files mdns_minimal [NOTFOUND=return] dns` to `/etc/nsswitch.conf`. Therefore I suggest to close (and not implement) this bug report.
