### ISSUE TITLE
Automatically disable ControlMaster for long hostnames

### ISSUE THREAD

**Issue by moul** [moul/advanced-ssh-config#91]
To avoid this kind of errors:

```
unix_listener: "/Users/moul/tmp/.ssh/cm/xxxx-xxxx-xxxx-xxx-xxxx-xxx-.members.btmm.icloud.com-22-moul.sock.qgFVXqlJOs9dCpUH" too long for Unix domain socket
```

**Comment by MerlinDMC** [comment]
@moul Since openssh 6.7 `%C` can be used as a replacement for `%r@%h:%p` which circumvents the long socket name problem.

```
 * ssh(1): Add a %C escape sequence for LocalCommand and ControlPath
   that expands to a unique identifer based on a hash of the tuple of
   (local host, remote user, hostname, port). Helps avoid exceeding
   miserly pathname limits for Unix domain sockets in multiplexing
   control paths; bz#2220
```

source: http://www.openssh.com/txt/release-6.7

**Comment by moul** [comment]
Super nice, thanks

Closing this

**Comment by moul** [comment]
@MerlinDMC would you like to update the [example in the `README.md` file](https://github.com/moul/advanced-ssh-config/commit/d6daac22f5b9510a101cfc4cb24a878443273370?diff=unified#diff-04c6e90faac2675aa89e2176d2eec7d8R139) ?

**Comment by MerlinDMC** [comment]
could do that in about 9 hours ... but if you want to put in before then go for it

**Comment by moul** [comment]
I prefer that you author the change, I can wait :)
